"""
AI Resume Generator Service
Uses Google Gemini API (free) to generate optimized resumes
"""

import os
from typing import Dict


def generate_optimized_resume(original_resume: str, job_description: str) -> Dict[str, any]:
    """
    Generate an optimized resume using Google Gemini API (free tier)
    """
    api_key = os.getenv('GEMINI_API_KEY')

    if not api_key:
        return {
            'success': False,
            'error': 'GEMINI_API_KEY not found. Get free key at https://aistudio.google.com/app/apikey'
        }

    prompt = f"""You are an expert resume writer and career coach. Optimize the following resume to better match the given job description.

IMPORTANT RULES:
1. DO NOT fabricate or add any information not present in the original resume
2. DO NOT invent skills, experiences, or qualifications
3. Only reorganize, rephrase, and highlight existing information
4. Emphasize relevant skills and experiences that match the job description
5. Use strong action verbs and quantifiable achievements where they already exist
6. Maintain professional formatting and structure

ORIGINAL RESUME:
{original_resume}

JOB DESCRIPTION:
{job_description}

Return ONLY the optimized resume text, without any additional commentary or explanations."""

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash')

        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                max_output_tokens=4096,
                temperature=0.7,
            )
        )

        optimized_resume = response.text
        return {
            'success': True,
            'optimized_resume': optimized_resume
        }

    except Exception as e:
        error_msg = str(e)
        if 'API_KEY_INVALID' in error_msg or 'invalid' in error_msg.lower():
            return {'success': False, 'error': 'Invalid GEMINI_API_KEY. Please check your key.'}
        elif 'quota' in error_msg.lower():
            return {'success': False, 'error': 'Gemini API quota exceeded. Try again later.'}
        return {'success': False, 'error': f'Gemini API error: {error_msg}'}


def format_resume_for_download(resume_text: str, filename: str) -> str:
    header  = "AI-OPTIMIZED RESUME\n"
    header += "Generated by Smart Resume Screener\n"
    header += f"Based on: {filename}\n"
    header += "=" * 80 + "\n\n"
    return header + resume_text
