"""
AI Resume Generator Service
Uses Google Gemini API (free) to generate optimized resumes
"""

import os
from typing import Dict


def _call_gemini(prompt: str) -> str:
    """Call Gemini API and return text response"""
    from google import genai
    from google.genai import types

    api_key = os.getenv('GEMINI_API_KEY')
    client  = genai.Client(api_key=api_key)

    # Try models in order of preference
    models = ['gemini-2.5-flash', 'gemini-2.0-flash-001', 'gemini-2.0-flash', 'gemini-flash-latest', 'gemini-2.5-flash-lite']
    last_error = None

    for model in models:
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=4096,
                    temperature=0.7,
                )
            )
            return response.text
        except Exception as e:
            last_error = e
            if '429' in str(e) or 'RESOURCE_EXHAUSTED' in str(e) or '503' in str(e) or 'UNAVAILABLE' in str(e):
                continue  # try next model
            raise e

    raise last_error


def generate_optimized_resume(original_resume: str, job_description: str) -> Dict[str, any]:
    """Generate an optimized resume using Google Gemini API (free tier)"""
    api_key = os.getenv('GEMINI_API_KEY')

    if not api_key:
        return {
            'success': False,
            'error': 'GEMINI_API_KEY not found. Get free key at https://aistudio.google.com/app/apikey'
        }

    prompt = f"""You are an expert resume writer and career coach. Optimize the following resume to better match the given job description.

IMPORTANT RULES:
1. DO NOT fabricate or add any information not present in the original resume
2. DO NOT invent skills, experiences, or qualifications
3. Only reorganize, rephrase, and highlight existing information
4. Emphasize relevant skills and experiences that match the job description
5. Use strong action verbs and quantifiable achievements where they already exist
6. Maintain professional formatting and structure

ORIGINAL RESUME:
{original_resume}

JOB DESCRIPTION:
{job_description}

Return ONLY the optimized resume text, without any additional commentary or explanations."""

    try:
        optimized_resume = _call_gemini(prompt)
        return {'success': True, 'optimized_resume': optimized_resume}

    except Exception as e:
        error_msg = str(e)
        if '429' in error_msg or 'RESOURCE_EXHAUSTED' in error_msg:
            return {'success': False, 'error': 'Gemini API quota exceeded. Please wait a minute and try again.'}
        if '503' in error_msg or 'UNAVAILABLE' in error_msg:
            return {'success': False, 'error': 'Gemini is temporarily overloaded. Please click Try Again in a few seconds.'}
        if 'API_KEY_INVALID' in error_msg or 'invalid' in error_msg.lower():
            return {'success': False, 'error': 'Invalid GEMINI_API_KEY. Please check your key.'}
        return {'success': False, 'error': f'Gemini API error: {error_msg}'}


def format_resume_for_download(resume_text: str, filename: str) -> str:
    header  = "AI-OPTIMIZED RESUME\n"
    header += "Generated by Smart Resume Screener\n"
    header += f"Based on: {filename}\n"
    header += "=" * 80 + "\n\n"
    return header + resume_text
