"""
Resume Roast Generator Service
Uses Google Gemini API (free) to roast resumes and provide fixed versions
"""

import os
from typing import Dict


def _call_gemini(prompt: str) -> str:
    """Call Gemini API and return text response"""
    from google import genai
    from google.genai import types

    api_key = os.getenv('GEMINI_API_KEY')
    client  = genai.Client(api_key=api_key)

    # Try models in order of preference
    models = ['gemini-2.5-flash', 'gemini-2.0-flash-lite', 'gemini-2.0-flash']
    last_error = None

    for model in models:
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=4096,
                    temperature=0.9,
                )
            )
            return response.text
        except Exception as e:
            last_error = e
            if '429' in str(e) or 'RESOURCE_EXHAUSTED' in str(e):
                continue  # try next model
            raise e

    raise last_error


def generate_roast(resume_text: str, job_description: str) -> Dict[str, any]:
    """Generate a brutal but funny roast of the resume, then provide a fixed version"""
    api_key = os.getenv('GEMINI_API_KEY')

    if not api_key:
        return {
            'success': False,
            'error': 'GEMINI_API_KEY not found. Get free key at https://aistudio.google.com/app/apikey'
        }

    prompt = f"""You are a brutally honest but hilarious HR expert who roasts resumes.

PART 1 - ROAST MODE 💀
Roast this resume mercilessly but professionally. Call out:
- Vague objectives and generic buzzwords ("team player", "hard worker")
- Weak job descriptions with no impact or metrics
- Missing keywords from the job description
- Formatting issues and inconsistencies
- Overused phrases and clichés

Be specific, witty, and harsh but keep it professional. Use emoji. Give 5-7 specific roast points as a numbered list.

PART 2 - FIXED VERSION ✅
Rewrite EVERY section you criticized. Make it:
- Sharp and specific with real impact
- ATS-friendly with relevant keywords from the JD
- Quantified where possible
- Tailored to the job description

---

RESUME TO ROAST:
{resume_text}

JOB DESCRIPTION:
{job_description}

---

Format your response EXACTLY like this:

🔥 ROAST MODE 💀

1. [First roast point with emoji]
2. [Second roast point with emoji]
3. [Third roast point with emoji]
(5-7 points total)

---FIXED VERSION---

[Complete rewritten resume here]"""

    try:
        full_response = _call_gemini(prompt)

        # Split roast and fixed version
        if '---FIXED VERSION---' in full_response:
            parts = full_response.split('---FIXED VERSION---', 1)
            roast_text = parts[0].strip()
            fixed_text = parts[1].strip()
        elif 'FIXED VERSION' in full_response:
            parts = full_response.split('FIXED VERSION', 1)
            roast_text = parts[0].strip()
            fixed_text = parts[1].strip()
        else:
            roast_text = full_response
            fixed_text = "Could not parse fixed version. Please try again."

        return {'success': True, 'roast': roast_text, 'fixed': fixed_text}

    except Exception as e:
        error_msg = str(e)
        if '429' in error_msg or 'RESOURCE_EXHAUSTED' in error_msg:
            return {'success': False, 'error': 'Gemini API quota exceeded on all models. Please wait a minute and try again.'}
        if 'API_KEY_INVALID' in error_msg or 'invalid' in error_msg.lower():
            return {'success': False, 'error': 'Invalid GEMINI_API_KEY. Please check your key.'}
        return {'success': False, 'error': f'Gemini API error: {error_msg}'}


def format_roast_for_download(fixed_text: str, filename: str) -> str:
    header  = "ROASTED & FIXED RESUME\n"
    header += "Generated by Smart Resume Screener - Roast Mode 💀\n"
    header += f"Based on: {filename}\n"
    header += "=" * 80 + "\n\n"
    return header + fixed_text
