"""
Resume Roast Generator Service
Uses Anthropic Claude API to roast resumes and provide fixed versions
"""

import os
import requests
from typing import Dict


def generate_roast(resume_text: str, job_description: str) -> Dict[str, any]:
    """
    Generate a brutal but funny roast of the resume, then provide a fixed version
    
    Args:
        resume_text: Original resume text
        job_description: Target job description
        
    Returns:
        Dictionary with 'success', 'roast', 'fixed', and optional 'error'
    """
    api_key = os.getenv('ANTHROPIC_API_KEY')
    
    if not api_key:
        return {
            'success': False,
            'error': 'ANTHROPIC_API_KEY not found in environment variables'
        }
    
    # Construct the roast prompt
    prompt = f"""You are a brutally honest but hilarious HR expert who roasts resumes. Your job is to:

PART 1 - ROAST MODE 💀
Roast this resume mercilessly but professionally. Call out:
- Vague objectives and generic buzzwords ("team player", "hard worker")
- Weak job descriptions with no impact or metrics
- Missing keywords from the job description
- Formatting issues and inconsistencies
- Overused phrases and clichés
- Anything that makes you cringe

Be specific, witty, and harsh but keep it professional. Use emoji. Give 5-7 specific roast points as a numbered list.

PART 2 - FIXED VERSION ✅
After roasting, rewrite EVERY section you criticized. Make it:
- Sharp and specific with real impact
- ATS-friendly with relevant keywords from the JD
- Quantified where possible
- Tailored to the job description
- Professional and compelling

Show the complete improved version of the resume.

---

RESUME TO ROAST:
{resume_text}

JOB DESCRIPTION:
{job_description}

---

Format your response EXACTLY like this:

🔥 ROAST MODE 💀

1. [First roast point with emoji]
2. [Second roast point with emoji]
3. [Third roast point with emoji]
... (5-7 points total)

---FIXED VERSION---

[Complete rewritten resume here]

Remember: Be brutally honest in the roast, then show them how it's done in the fixed version!"""

    # Call Claude API
    try:
        response = requests.post(
            'https://api.anthropic.com/v1/messages',
            headers={
                'x-api-key': api_key,
                'anthropic-version': '2023-06-01',
                'content-type': 'application/json'
            },
            json={
                'model': 'claude-sonnet-4-20250514',
                'max_tokens': 4096,
                'messages': [
                    {
                        'role': 'user',
                        'content': prompt
                    }
                ]
            },
            timeout=90
        )
        
        response.raise_for_status()
        
        data = response.json()
        
        # Extract the response
        if 'content' in data and len(data['content']) > 0:
            full_response = data['content'][0]['text']
            
            # Split by the separator
            if '---FIXED VERSION---' in full_response:
                parts = full_response.split('---FIXED VERSION---', 1)
                roast_text = parts[0].strip()
                fixed_text = parts[1].strip()
            elif 'FIXED VERSION' in full_response:
                parts = full_response.split('FIXED VERSION', 1)
                roast_text = parts[0].strip()
                fixed_text = parts[1].strip()
            else:
                # Fallback: try to split by common patterns
                roast_text = full_response
                fixed_text = "Could not parse fixed version. Please try again."
            
            return {
                'success': True,
                'roast': roast_text,
                'fixed': fixed_text
            }
        else:
            return {
                'success': False,
                'error': 'Unexpected response format from Claude API'
            }
            
    except requests.exceptions.Timeout:
        return {
            'success': False,
            'error': 'Request to Claude API timed out. Please try again.'
        }
    except requests.exceptions.RequestException as e:
        return {
            'success': False,
            'error': f'API request failed: {str(e)}'
        }
    except Exception as e:
        return {
            'success': False,
            'error': f'Unexpected error: {str(e)}'
        }


def format_roast_for_download(fixed_text: str, filename: str) -> str:
    """
    Format fixed resume for download
    
    Args:
        fixed_text: The fixed resume content
        filename: Original filename for reference
        
    Returns:
        Formatted text ready for download
    """
    header = f"ROASTED & FIXED RESUME\n"
    header += f"Generated by Smart Resume Screener - Roast Mode 💀\n"
    header += f"Based on: {filename}\n"
    header += "=" * 80 + "\n\n"
    
    return header + fixed_text
